DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION

if VERSION[0:2] > (1, 3):
    from django.conf.urls import patterns, url
else:
    from django.conf.urls.defaults import patterns, url


from .views import get_ueditor_controller

urlpatterns = patterns('',
    url(r'^controller/$', get_ueditor_controller)
)

minicms/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
import sys

from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.views.decorators.cache import cache_page
from django.contrib.sitemaps import views as sitemaps_views

sys.path.append(settings.BASE_DIR)
from DjangoUeditor import urls as DjangoUeditor_urls
from news import views
from news.models import Article,Column

sitemaps = {
    'blog': GenericSitemap({'queryset': Article.objects.all(), 'date_field': 'pub_date'}, priority=0.6),
    'news':GenericSitemap({'queryset': Article.objects.all(),'update_time':'pub_date'},priority = 0.6),
    # 如果还要加其它的可以模仿上面的
}


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^user/$',views.userinfo,name='userinfo'),
    url(r'^video/(?P<pk>[^/]+)/$',views.video,name='video'),
    url(r'^admin/', admin.site.urls),
    url(r'^ueditor/', include(DjangoUeditor_urls)),
    url(r'^column/(?P<column_slug>[^/]+)/$',views.column_detail,name='column'),
    url(r'^news/(?P<pk>\d+)/(?P<article_slug>[^/]+)/$',views.article_detail,name='article'),
    url(r'^api/$',views.api,name='api'),
    url(r'^api/(?P<pk>\d+)/$',views.apiPk,name='api'),
    # 但是这样生成的 sitemap，如果网站内容太多就很慢，很耗费资源，可以采用分页的功能：
    #url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        #name='django.contrib.sitemaps.views.sitemap'),
]
"""
   url(r'^sitemap\.xml$',
       cache_page(86400)(sitemaps_views.index),
       {'sitemaps': sitemaps, 'sitemap_url_name': 'sitemaps'}),
   url(r'^sitemap-(?P<section>.+)\.xml$',
       cache_page(86400)(sitemaps_views.sitemap),
       {'sitemaps': sitemaps}, name='sitemaps'),
   """



if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
# -*- coding:utf-8 -*-
from __future__ import unicode_literals

import time
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from DjangoUeditor.models import UEditorField


@python_2_unicode_compatible
class Column(models.Model):
    name = models.CharField(u'栏目名称',max_length=256)
    slug = models.CharField(u'栏目网址',max_length=256,db_index=True)
    intro = models.TextField(u'栏目简介',default='')

    #添加导航
    nav_display = models.BooleanField(u'导航显示',default=False)
    home_display = models.BooleanField(u'首页显示',default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('column',args=(self.slug,))

    class Meta:
        verbose_name = '新闻分组'
        verbose_name_plural = '新闻分组'
        ordering = ['name'] #按照哪个栏目排序

@python_2_unicode_compatible
class Photo(models.Model):
    name = models.CharField(u'图片名称', max_length=256)
    image = models.FileField(u'图片', upload_to='Images', max_length=100)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '图片路径'
        verbose_name_plural = '图片路径'

@python_2_unicode_compatible
class Article(models.Model):
    column = models.ManyToManyField(Column, verbose_name = '归属栏目')
    photo = models.ManyToManyField(Photo,verbose_name = '图片')
    title = models.CharField(u'标题',max_length=256)
    slug = models.CharField(u'网址',max_length=256)

    author = models.ForeignKey('auth.User',blank=True,null=True,verbose_name='作者')
    keyword = models.CharField(u'关键字', max_length=256,default='')
    content = UEditorField(u'内容',height=300,width=1000,
                           default=u'',blank=True,imagePath="uploads/images/",
                           toolbars='besttome',filePath='uploads/files/')
        #models.TextField(u'内容',default='',blank=True)
    image = models.FileField(u'图片路径',upload_to='Images', max_length=100)
    published = models.BooleanField(u'正式发布',default=True)

    pub_date = models.DateTimeField(u'发表时间',auto_now_add=True,editable=True)
    update_time = models.DateTimeField(u'更新时间',auto_now=True,null=True)


    def __str__(self):
        return  self.title

    def get_absolute_url(self):
        return reverse('article',args=(self.pk,self.slug,))

    def getPub_date(self):
        return time.strftime("%Y-%m-%d %H:%M:%S",time.mktime(self.pub_date))

    class Meta:
        verbose_name = '新闻文章'
        verbose_name_plural = '新闻文章'

@python_2_unicode_compatible
class Video(models.Model):
    name = models.CharField(u'视频名称', max_length=256)
    path = models.CharField(u'视频路径', max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('video',args=(self.pk,))


    class Meta:
        verbose_name = '视频集合'
        verbose_name_plural = '视频集合'

news/views.py
# !/user/bin/python
# -*- coding: utf-8 -*-
'''
Created by zhangyh2 on 2016/9/7
@TODO: 对页面进行反馈和绑定
'''
import json

import simplejson
from django.core import serializers
from django.core.serializers import serialize
from django.db.models import QuerySet
from django.http import HttpResponse
from django.shortcuts import render, redirect

# 首页 index   栏目 column    文章详情   article

from news.models import Column, Video, Article

from news.common.JsonUtils import toJsonStr


def userinfo(request):
    name = '123'
    age = 23
    return render(request, 'user_info.html', {'name': name, 'age': age})


'''
实现接口请求
'''


def api(request):
    art = Article.objects.all()
    return HttpResponse(toJsonStr(art))


def apiPk(request, pk):
    article = toJsonStr(Article.objects.get(pk=pk))
    print(article)
    return HttpResponse(article)


def index(request):
    home_display_columns = Column.objects.filter(home_display=True)
    nav_display_columns = Column.objects.filter(nav_display=True)
    videos = Video.objects.filter()[0]
    return render(request, 'index.html', {
        'home_display_columns': home_display_columns,
        'nav_display_columns': nav_display_columns,
        'video': videos,
    })
    # columns = Column.objects.all()
    # return render(request,'index.html',{'columns':columns})


def video(request, pk):
    videos = Video.objects.filter()
    return render(request, 'news/video.html', {'video': videos})


def column_detail(request, column_slug):
    column = Column.objects.get(slug=column_slug)
    return render(request, 'news/column.html', {'column': column})


def article_detail(request, pk, article_slug):
    host = request.get_host()
    article = Article.objects.get(pk=pk)
    if article_slug != article.slug:
        return redirect(article, permanent=True)
    try:
        previous_page = Article.objects.get(pk=int(article.id) - 1).get_absolute_url()
    except:
        previous_page = None
    try:
        next_page = Article.objects.get(pk=int(article.id) + 1).get_absolute_url()
    except:
        next_page = None
    articles = Article.objects.filter(keyword__contains=article.keyword)

    if len(articles) > 1:
        return render(request, 'news/article.html', {
            'article': article, 'column': article.column.all()[0],
            'previous_page': previous_page,
            'next_page': next_page,
            'recommend': articles,
            'recommend0': False,
            'host': host,
            'photo': article.photo.all(), })

    return render(request, 'news/article.html', {
        'article': article, 'column': article.column.all()[0],
        'previous_page': previous_page,
        'next_page': next_page,
        'recommend': articles,
        'recommend0': True,
        'host': host,
        'photo': article.photo.all(),
    })

news/templates/news/article.html
<style>
    body,ul,li{ padding:0; margin:0;}
    ul,li{ list-style:none;}
    img{ border:none;}
    a{ color:#6cf;}
    a:hover{ color:#84B263;}
    .box{ width:980px; margin:0 auto; position:relative; overflow:hidden; _height:100%;}
    .picbox{ width:980px; height:130px; overflow:hidden; position:relative;}
    .piclist{ height:130px;position:absolute; left:0px; top:0px}
    .piclist li{ background:#eee; margin-right:20px; padding:5px; float:left;}
    .swaplist{ position:absolute; left:-3000px; top:0px}
    .og_prev,.og_next{ width:30px; height:50px; background:#84B263 no-repeat; background:#84B263 no-repeat\9; position:absolute; top:33px; z-index:99; cursor:pointer;filter:alpha(opacity=70); opacity:0.7;}
    .og_prev{ background-position:0 -60px; left:4px;}
    .og_next{ background-position:0 0; right:4px;}
</style>
<script type="text/javascript" src="/media/jquery/jquery-1.12.3.min.js"></script>
<script type="text/javascript">
$(document).ready(function(e) {
	/***不需要自动滚动，去掉即可***/
//	time = window.setInterval(function(){
//		$('.og_next').click();
//	},3000);
	/***不需要自动滚动，去掉即可***/
	linum = $('.mainlist li').length;//图片数量
	w = linum * 250;//ul宽度
	$('.piclist').css('width', w + 'px');//ul宽度
	$('.swaplist').html($('.mainlist').html());//复制内容
	$('.og_next').click(function(){
		if($('.swaplist,.mainlist').is(':animated')){
			$('.swaplist,.mainlist').stop(true,true);
		}
		if($('.mainlist li').length>4){//多于4张图片
			ml = parseInt($('.mainlist').css('left'));//默认图片ul位置
			sl = parseInt($('.swaplist').css('left'));//交换图片ul位置
			if(ml<=0 && ml>w*-1){//默认图片显示时
				$('.swaplist').css({left: '1000px'});//交换图片放在显示区域右侧
				$('.mainlist').animate({left: ml - 1000 + 'px'},'slow');//默认图片滚动
				if(ml==(w-1000)*-1){//默认图片最后一屏时
					$('.swaplist').animate({left: '0px'},'slow');//交换图片滚动
				}
			}else{//交换图片显示时
				$('.mainlist').css({left: '1000px'})//默认图片放在显示区域右
				$('.swaplist').animate({left: sl - 1000 + 'px'},'slow');//交换图片滚动
				if(sl==(w-1000)*-1){//交换图片最后一屏时
					$('.mainlist').animate({left: '0px'},'slow');//默认图片滚动
				}
			}
		}
	})
	$('.og_prev').click(function(){

		if($('.swaplist,.mainlist').is(':animated')){
			$('.swaplist,.mainlist').stop(true,true);
		}
		if($('.mainlist li').length>4){
			ml = parseInt($('.mainlist').css('left'));
			sl = parseInt($('.swaplist').css('left'));
			if(ml<=0 && ml>w*-1){
				$('.swaplist').css({left: w * -1 + 'px'});
				$('.mainlist').animate({left: ml + 1000 + 'px'},'slow');
				if(ml==0){
					$('.swaplist').animate({left: (w - 1000) * -1 + 'px'},'slow');
				}
			}else{
				$('.mainlist').css({left: (w - 1000) * -1 + 'px'});
				$('.swaplist').animate({left: sl + 1000 + 'px'},'slow');
				if(sl==0){
					$('.mainlist').animate({left: '0px'},'slow');
				}
			}
		}
	})
});
$(document).ready(function(){
	$('.og_prev,.og_next').hover(function(){
			$(this).fadeTo('fast',1);
		},function(){
			$(this).fadeTo('fast',0.7);
	})
})
</script>

<style type="text/css">
    .footser p{font:normal 16px/2em '新宋体';text-align:center;}
</style>
{% extends "base.html" %}
{% block title %}
{{ article.title }}
{% endblock title %}
{% block content %}
<div id="title">
    <div class="titles"  align="center">
    <h1>{{ article.title }}</h1>
    </div>
    <div class="content" align="center">
    <b><a href="{{ column.get_absolute_url }}">{{ column }}</a>&nbsp{{ article.author }}提供&nbsp{{ article.pub_date}}</b>
    </div>
</div>

    <div align="center">
        {% if not photo %}
            <div align="center">
                 <img src="http://{{ host }}/media/{{article.image}}" style="width: 50%;text-align: center">
             </div>
        {% else %}
            {% for pho in photo %}
                 <div align="center">
                     <img src="http://{{ host }}/media/{{pho.image}}" style="width: 50%;text-align: center">
                 </div>
                <div style="padding: 10px;width: 50%; text-align: left"  class="content">
                    <p>{{ pho.name }}</p>
                </div>
            {% endfor %}
        {% endif %}
        <div style="padding: 10px;width: 50%; text-align: left"  class="content" >
            <p escape="false" >{{ article.content }}</p>
        </div>
    </div>
<div align="center">
    {% if not previous_page%}
    {% else %}
    <span align="left">
        <a href="{{previous_page}}">上一页</a>&nbsp&nbsp
    </span>
    {% endif %}
    {% if not next_page%}
    {% else %}
    <span align="right">
        &nbsp&nbsp<a href="{{next_page}}">下一页</a>
    </span>
    {% endif %}
</div>
<!--推荐新闻 数量未知，可进行扩展-->
    {% if recommend0 %}
    {% else %}
        <hr>
        <div class="footser">
        <p>推荐新闻：</p>
        </div>
        <div class="box">
        <div class="picbox">
            <ul class="piclist mainlist">
            {% for art in recommend %}
            {% ifequal art.title article.title %}
            {% else %}
                <li>
                <a href="{{ art.get_absolute_url }}">
                    <div>
                    <img src="http://{{ host }}/media/{{art.image}}" style="width: 220px;height: 105px">
                    </div>
                    <div align="center">
                    <span>{{art}}</span>
                    </div>
                </a>
                </li>
            {% endifequal %}
            {% endfor %}
            </ul>
            <ul class="piclist swaplist"></ul>
        </div>
        <div class="og_prev"></div>
        <div class="og_next"></div>
    {% endif %}
{% endblock content %}

news/templates/news/column.html
{% extends "base.html" %}
 
{% block title %}
{{ column.title }}
{% endblock title %}
 
{% block content %}
<p>{{column.name}}</p>
<p>简介：{{ column.intro }}</p>
<p>列表：</p>
<ol align="center">
    {% for article in column.article_set.all %}
    <li>
        <a href="{{ article.get_absolute_url }}" >{{ article.title }}</a>
    </li>
    {% endfor %}
</ol>
还需要完善

{% endblock content %}

news/templates/news/video.html
{% extends "base.html" %}
 
{% block title %}
{{ column.title }}
{% endblock title %}
 
{% block content %}
<p>{{video.name}}</p>
    <ol align="center">
    {% for vv in video %}
    <li>
        <a href="{{ article.get_absolute_url }}" >{{ vv.name }}</a>
    </li>
    {% endfor %}
</ol>

{% endblock content %}